consts:
  dt: 0.005
  particle_radius: 0.01
  wall_collision_decay: 0.2
  particle_mass: 0.5
  spring_overlap_balance: 0.1
  spring_amplifier: 5000
  pressure_amplifier: 2000
  ignored_pressure: 0.1
  collider_noise_level: 0.2
  wall_virtual_mass_factor: 3
  viscosity: 8
  gravity: [ 0, 9.8 ]
  max_particles: 1000

particle_sources:
  - radius: 0.15
    position: [ 0.1, 0.1 ]
    velocity: [ 1.3, 0.0 ]
    flow: 300
    particle_mass: 1.0
    noise: 0.01

rigid_bodies:
  - fixed:
      name: edge
      segments: [
        [ [ 0.0, 0.0 ], [ 0.0, 1.0 ] ],
        [ [ 0.0, 0.0 ], [ 1.0, 0.0 ] ],
        [ [ 1.0, 0.0 ], [ 1.0, 1.0 ] ],
        #        [ [ 0.0, 1.0 ], [ 1.0, 1.0 ] ],
      ]
  #- motored:
  #    name: box
  #    segments: [
  #      [ [ 0.55, 1.0 ], [ 0.55, 0.8 ] ],
  #      [ [ 0.55, 1.0 ], [ 0.6, 1.0 ] ],
  #      [ [ 0.6, 1.0 ], [ 0.6, 0.8 ] ],
  #      [ [ 0.55, 0.8 ], [ 0.6, 0.8 ] ],
  #    ]
  #    velocity_func: "lambda t: np.sin(t * 30) * np.array([1.0, 0.0])"
  - motored:
      name: moving_cup
      segments: [
        [ [ 0.0, 0.0 ], [ 0.0, 1.0 ] ],
        #        [ [ 0.0, 0.0 ], [ 1.0, 0.0 ] ],
        [ [ 1.0, 0.0 ], [ 1.0, 1.0 ] ],
        [ [ 0.0, 1.0 ], [ 1.0, 1.0 ] ],
      ]
      angular_velocity_func: "lambda t: np.cos(t * 4)"
      scale: [ 0.2, 0.1 ]
      position: [ 0.3, 0.5 ]
