playback:
  live_simulation: false
  ticks_to_record: 10000
  recording_output_dir_path: "../data/recording"
world:
  consts:
    dt: 0.001
    particle_radius: 0.005
    wall_collision_decay: 0.4
    particle_mass: 0.5
    spring_overlap_balance: 0.1
    spring_amplifier: 8000
    pressure_amplifier: 2500
    ignored_pressure: 0.3
    collider_noise_level: 0.2
    wall_virtual_mass_factor: 3
    viscosity: 8
    gravity: [ 0, 9.8 ]
    max_particles: 2000

  particle_sources:
    - radius: 0.05
      position: [ 0.9, 0.1 ]
      velocity: [ -2.5, 1.0 ]
      flow: 500
      particle_mass: 1.0
      noise: 0

  rigid_bodies:
    - fixed:
        name: edge
        segments: [
          [ [ 0.0, 0.0 ], [ 0.0, 1.0 ] ],
          [ [ 0.0, 0.0 ], [ 1.0, 0.0 ] ],
          [ [ 1.0, 0.0 ], [ 1.0, 1.0 ] ],
        ]
    - motored:
        name: moving_cup
        segments: [
          [ [ 0.0, 0.0 ], [ 0.0, 1.0 ] ],
          [ [ 1.0, 0.0 ], [ 1.0, 1.0 ] ],
          [ [ 0.0, 1.0 ], [ 1.0, 1.0 ] ],
        ]
        angular_velocity_func: "lambda t: np.cos(t * 4)*1.4"
        scale: [ 0.3, 0.15 ]
        position: [ 0.3, 0.5 ]
    - fixed:
        name: buttom_cup
        segments: [
          [ [ 0.0, 0.0 ], [ 0.0, 1.0 ] ],
          [ [ 1.0, 0.0 ], [ 1.0, 1.0 ] ],
          [ [ 0.0, 1.0 ], [ 1.0, 1.0 ] ],
        ]
        scale: [ 0.8, 0.05 ]
        position: [ 0.1, 0.9 ]
